<?php

// administrative roles defined
$array_gender=array();
$array_gender['Male']="Male";
$array_gender['Female']="Female";

$array_emp_team_role=array();
$array_emp_team_role['Standard']="Standard";
$array_emp_team_role['Admin']="Super User";

$array_signinasadmin=array();
$array_signinasadmin['C']="Consumer";
$array_signinasadmin['SP']="Frentor";
$array_signinasadmin['B']="Both";

$array_subscribe_period=array();
$array_subscribe_period['Daily']="Daily";
$array_subscribe_period['Weekly']="Weekly";
$array_subscribe_period['Monthly']="Monthly";

$array_salary_period=array();
$array_salary_period['Per Month']="Per Month";
$array_salary_period['Per Day']="Per Day";

$array_salary_currency=array();
$array_salary_currency['AUD']="AUD";
$array_salary_currency['EURO']="EURO";
$array_salary_currency['GBP']="GBP";
$array_salary_currency['USD']="USD";

// administrative roles defined
$array_roles=array();
$array_roles['orders']="Manage Orders";
$array_roles['vendors']="Manage Vendors";
$array_roles['vcd']="Manage Vendors Credit/Debit";
$array_roles['complain']="Manage Complain";
$array_roles['content']="Manage Static Content";
$array_roles['system']="Manage System";
$array_roles['users']="Manage Users";
$array_roles['usersgroup']="Manage Users Groups";
$array_roles['addupdatevendros']="Add Vendors";
$array_roles['generalsetting']="Website Settings (Only for admin users)";

// administrative roles defined
$array_marital_status=array();
$array_marital_status['not_married']="Not Married";
$array_marital_status['married']="Married";
$array_marital_status['widowed']="Widowed";
$array_marital_status['divorced_saparated']="Divorced/Separated";

$array_boolean=array();
$array_boolean['yes']="Yes";
$array_boolean['no']="No";

$array_duration=array();
$array_duration['Entire_Year']="Entire Year";
$array_duration['Seasonal']="Seasonal";

$array_modetransport=array();
$array_modetransport['Bus']="Bus";
$array_modetransport['shared_auto']="Shared Auto";
$array_modetransport['jeep']="Jeep";
$array_modetransport['other']="Any Other";

$array_transportavailability=array();
$array_transportavailability['frequent']="Frequent";
$array_transportavailability['not_frequent']="Not Frequent";
$array_transportavailability['only_two_times_a_day ']="Only Two Times a Day ";
$array_transportavailability['other']="Any Other";

$array_days=array();
$array_days['Monday']="Monday";
$array_days['Tuesday']="Tuesday";
$array_days['Wednesday ']="Wednesday";
$array_days['Thursday']="Thursday";
$array_days['Friday']="Friday";
$array_days['Saturday ']="Saturday";
$array_days['Sunday']="Sunday";

$array_months=array();
$array_months['January']="January";
$array_months['February']="February";
$array_months['March']="March";
$array_months['April']="April";
$array_months['May']="May";
$array_months['June']="June";
$array_months['July']="July";
$array_months['August']="August";
$array_months['September']="September";
$array_months['October']="October";
$array_months['November ']="November";
$array_months['December']="December";

$array_months_number=array();
$array_months_number['January']="1";
$array_months_number['February']="2";
$array_months_number['March']="3";
$array_months_number['April']="4";
$array_months_number['May']="5";
$array_months_number['June']="6";
$array_months_number['July']="7";
$array_months_number['August']="8";
$array_months_number['September']="9";
$array_months_number['October']="10";
$array_months_number['November ']="11";
$array_months_number['December']="12";

$array_daysnew=array();
$array_daysnew['m']="Monday";
$array_daysnew['t']="Tuesday";
$array_daysnew['w']="Wednesday";
$array_daysnew['th']="Thursday";
$array_daysnew['f']="Friday";
$array_daysnew['s ']="Saturday";
$array_daysnew['su']="Sunday";

$arrayuser_rating=array();
$arrayuser_rating[1]='<i class="fa fa-smile-o" aria-hidden="true"></i> Good';
$arrayuser_rating[2]='<i class="fa fa-meh-o" aria-hidden="true"></i> Okey';
$arrayuser_rating[3]='<i class="fa fa-frown-o" aria-hidden="true"></i> Bad';

$arrayuser_rating_2=array();
$arrayuser_rating_2[5]='Best';
$arrayuser_rating_2[4]='Better';
$arrayuser_rating_2[3]='Good';
$arrayuser_rating_2[2]='Okey';
$arrayuser_rating_2[1]='Bad';

$arrayuser_recomend=array();
$arrayuser_recomend[1]='Yes';
$arrayuser_recomend[2]='No';









$array_shiptype=array();
$array_shiptype[1]='Accommodation Vessel';
$array_shiptype[2]='Anchor Handling (AHTS)';
$array_shiptype[3]='Bulk Carrier';
$array_shiptype[4]='Cable Laying Vessel';
$array_shiptype[5]='Chemical Tanker';
$array_shiptype[6]='Coaster';
$array_shiptype[7]='Construction Support Vessel (CSV)';
$array_shiptype[8]='Container Ship';
$array_shiptype[9]='Crew Boat';
$array_shiptype[10]='Cruise Ship';
$array_shiptype[11]='Dredger - Cutter Suction';
$array_shiptype[12]='Dredger - Hopper';
$array_shiptype[13]='Dredger - Other';
$array_shiptype[14]='Dredger - Trailing Suction';
$array_shiptype[15]='Drill Ship';
$array_shiptype[16]='Drilling Barge';
$array_shiptype[17]='Field and Subsea Support Vessel';
//$array_shiptype[18]='Fishing - Longliners';
//$array_shiptype[19]='Fishing - Other';
//$array_shiptype[20]='Fishing - Seiners';
//$array_shiptype[21]='Fishing - Trawlers';
$array_shiptype[22]='Fixed Platform';
$array_shiptype[23]='Floating Hotel';
$array_shiptype[24]='FPSO';
$array_shiptype[25]='General Cargo';
$array_shiptype[26]='Harbour Tug';
$array_shiptype[27]='Ice Breaking Ship';
$array_shiptype[28]='Jack-up Barge';
$array_shiptype[29]='Jack-Up Rig';
$array_shiptype[30]='Live Stock Carrier';
$array_shiptype[30]='LNG Carrier';
$array_shiptype[31]='LPG Carrier';
$array_shiptype[32]='Multi Purpose Vessel';
$array_shiptype[33]='Ocean Tug';
$array_shiptype[34]='Offshore Supply Vessel(OSV)';
$array_shiptype[35]='Offshore Construction Vessel';
$array_shiptype[36]='Other';
$array_shiptype[37]='Oil Tanker';
$array_shiptype[38]='Passenger Ferry';
$array_shiptype[39]='Pilot Boat';
$array_shiptype[40]='Pipe Laying Vessel';
$array_shiptype[40]='Platform Supply Vessel(PSV)';
$array_shiptype[41]='Reefer Vessel';
$array_shiptype[42]='Rescue Vessel';
$array_shiptype[43]='Research Vessel';
//$array_shiptype[44]='River Barge';
//$array_shiptype[45]='River Tug';
$array_shiptype[46]='RORO';
//$array_shiptype[47]='RORO - GenRO';
//$array_shiptype[48]='RORO - Other';
//$array_shiptype[49]='RORO - PCC/PCTC';
//$array_shiptype[50]='RORO - RoPax';
$array_shiptype[50]='ROV Support vessel';
$array_shiptype[51]='Seismic Vessel';
$array_shiptype[52]='Semisubmersible Rig';
$array_shiptype[53]='Submersible Rig';
$array_shiptype[54]='Training Vessel';
$array_shiptype[55]='Tug Boat';
//$array_shiptype[56]='Well Boat';
//$array_shiptype[57]='Wind Farm - Crew Transfer';
//$array_shiptype[58]='Wind Farm - Installation Vessel';
//$array_shiptype[59]='Wind Farm - SOV Vessel';
//$array_shiptype[60]='Yacht';

$array_dpsystem=array();
$array_dpsystem[1]='DP System 1';
$array_dpsystem[2]='DP System 2';
$array_dpsystem[3]='DP System 3';
//$array_dpsystem[4]='DP System 4';

/*$array_countrycode=array();
$array_countrycode["+61"]='+61';
$array_countrycode["+62"]='+62';  */


$array_countrycode = array
(
	'0' => 'Country Code',
	'44' => 'UK (+44)',
	'1' => 'USA (+1)',
	'213' => 'Algeria (+213)',
	'376' => 'Andorra (+376)',
	'244' => 'Angola (+244)',
	'1264' => 'Anguilla (+1264)',
	'1268' => 'Antigua & Barbuda (+1268)',
	'54' => 'Argentina (+54)',
	'374' => 'Armenia (+374)',
	'297' => 'Aruba (+297)',
	'61' => 'Australia (+61)',
	'43' => 'Austria (+43)',
	'994' => 'Azerbaijan (+994)',
	'1242' => 'Bahamas (+1242)',
	'973' => 'Bahrain (+973)',
	'880' => 'Bangladesh (+880)',
	'1246' => 'Barbados (+1246)',
	'375' => 'Belarus (+375)',
	'32' => 'Belgium (+32)',
	'501' => 'Belize (+501)',
	'229' => 'Benin (+229)',
	'1441' => 'Bermuda (+1441)',
	'975' => 'Bhutan (+975)',
	'591' => 'Bolivia (+591)',
	'387' => 'Bosnia Herzegovina (+387)',
	'267' => 'Botswana (+267)',
	'55' => 'Brazil (+55)',
	'673' => 'Brunei (+673)',
	'359' => 'Bulgaria (+359)',
	'226' => 'Burkina Faso (+226)',
	'257' => 'Burundi (+257)',
	'855' => 'Cambodia (+855)',
	'237' => 'Cameroon (+237)',
	'1' => 'Canada (+1)',
	'238' => 'Cape Verde Islands (+238)',
	'1345' => 'Cayman Islands (+1345)',
	'236' => 'Central African Republic (+236)',
	'56' => 'Chile (+56)',
	'86' => 'China (+86)',
	'57' => 'Colombia (+57)',
	'269' => 'Comoros (+269)',
	'242' => 'Congo (+242)',
	'682' => 'Cook Islands (+682)',
	'506' => 'Costa Rica (+506)',
	'385' => 'Croatia (+385)',
	'53' => 'Cuba (+53)',
	'90392' => 'Cyprus North (+90392)',
	'357' => 'Cyprus South (+357)',
	'42' => 'Czech Republic (+42)',
	'45' => 'Denmark (+45)',
	'253' => 'Djibouti (+253)',
	'1809' => 'Dominica (+1809)',
	'1809' => 'Dominican Republic (+1809)',
	'593' => 'Ecuador (+593)',
	'20' => 'Egypt (+20)',
	'503' => 'El Salvador (+503)',
	'240' => 'Equatorial Guinea (+240)',
	'291' => 'Eritrea (+291)',
	'372' => 'Estonia (+372)',
	'251' => 'Ethiopia (+251)',
	'500' => 'Falkland Islands (+500)',
	'298' => 'Faroe Islands (+298)',
	'679' => 'Fiji (+679)',
	'358' => 'Finland (+358)',
	'33' => 'France (+33)',
	'594' => 'French Guiana (+594)',
	'689' => 'French Polynesia (+689)',
	'241' => 'Gabon (+241)',
	'220' => 'Gambia (+220)',
	'7880' => 'Georgia (+7880)',
	'49' => 'Germany (+49)',
	'233' => 'Ghana (+233)',
	'350' => 'Gibraltar (+350)',
	'30' => 'Greece (+30)',
	'299' => 'Greenland (+299)',
	'1473' => 'Grenada (+1473)',
	'590' => 'Guadeloupe (+590)',
	'671' => 'Guam (+671)',
	'502' => 'Guatemala (+502)',
	'224' => 'Guinea (+224)',
	'245' => 'Guinea - Bissau (+245)',
	'592' => 'Guyana (+592)',
	'509' => 'Haiti (+509)',
	'504' => 'Honduras (+504)',
	'852' => 'Hong Kong (+852)',
	'36' => 'Hungary (+36)',
	'354' => 'Iceland (+354)',
	'91' => 'India (+91)',
	'62' => 'Indonesia (+62)',
	'98' => 'Iran (+98)',
	'964' => 'Iraq (+964)',
	'353' => 'Ireland (+353)',
	'972' => 'Israel (+972)',
	'39' => 'Italy (+39)',
	'1876' => 'Jamaica (+1876)',
	'81' => 'Japan (+81)',
	'962' => 'Jordan (+962)',
	'7' => 'Kazakhstan (+7)',
	'254' => 'Kenya (+254)',
	'686' => 'Kiribati (+686)',
	'850' => 'Korea North (+850)',
	'82' => 'Korea South (+82)',
	'965' => 'Kuwait (+965)',
	'996' => 'Kyrgyzstan (+996)',
	'856' => 'Laos (+856)',
	'371' => 'Latvia (+371)',
	'961' => 'Lebanon (+961)',
	'266' => 'Lesotho (+266)',
	'231' => 'Liberia (+231)',
	'218' => 'Libya (+218)',
	'417' => 'Liechtenstein (+417)',
	'370' => 'Lithuania (+370)',
	'352' => 'Luxembourg (+352)',
	'853' => 'Macao (+853)',
	'389' => 'Macedonia (+389)',
	'261' => 'Madagascar (+261)',
	'265' => 'Malawi (+265)',
	'60' => 'Malaysia (+60)',
	'960' => 'Maldives (+960)',
	'223' => 'Mali (+223)',
	'356' => 'Malta (+356)',
	'692' => 'Marshall Islands (+692)',
	'596' => 'Martinique (+596)',
	'222' => 'Mauritania (+222)',
	'269' => 'Mayotte (+269)',
	'52' => 'Mexico (+52)',
	'691' => 'Micronesia (+691)',
	'373' => 'Moldova (+373)',
	'377' => 'Monaco (+377)',
	'976' => 'Mongolia (+976)',
	'1664' => 'Montserrat (+1664)',
	'212' => 'Morocco (+212)',
	'258' => 'Mozambique (+258)',
	'95' => 'Myanmar (+95)',
	'264' => 'Namibia (+264)',
	'674' => 'Nauru (+674)',
	'977' => 'Nepal (+977)',
	'31' => 'Netherlands (+31)',
	'687' => 'New Caledonia (+687)',
	'64' => 'New Zealand (+64)',
	'505' => 'Nicaragua (+505)',
	'227' => 'Niger (+227)',
	'234' => 'Nigeria (+234)',
	'683' => 'Niue (+683)',
	'672' => 'Norfolk Islands (+672)',
	'670' => 'Northern Marianas (+670)',
	'47' => 'Norway (+47)',
	'968' => 'Oman (+968)',
	'680' => 'Palau (+680)',
	'507' => 'Panama (+507)',
	'675' => 'Papua New Guinea (+675)',
	'595' => 'Paraguay (+595)',
	'51' => 'Peru (+51)',
	'63' => 'Philippines (+63)',
	'48' => 'Poland (+48)',
	'351' => 'Portugal (+351)',
	'1787' => 'Puerto Rico (+1787)',
	'974' => 'Qatar (+974)',
	'262' => 'Reunion (+262)',
	'40' => 'Romania (+40)',
	'7' => 'Russia (+7)',
	'250' => 'Rwanda (+250)',
	'378' => 'San Marino (+378)',
	'239' => 'Sao Tome & Principe (+239)',
	'966' => 'Saudi Arabia (+966)',
	'221' => 'Senegal (+221)',
	'381' => 'Serbia (+381)',
	'248' => 'Seychelles (+248)',
	'232' => 'Sierra Leone (+232)',
	'65' => 'Singapore (+65)',
	'421' => 'Slovak Republic (+421)',
	'386' => 'Slovenia (+386)',
	'677' => 'Solomon Islands (+677)',
	'252' => 'Somalia (+252)',
	'27' => 'South Africa (+27)',
	'34' => 'Spain (+34)',
	'94' => 'Sri Lanka (+94)',
	'290' => 'St. Helena (+290)',
	'1869' => 'St. Kitts (+1869)',
	'1758' => 'St. Lucia (+1758)',
	'249' => 'Sudan (+249)',
	'597' => 'Suriname (+597)',
	'268' => 'Swaziland (+268)',
	'46' => 'Sweden (+46)',
	'41' => 'Switzerland (+41)',
	'963' => 'Syria (+963)',
	'886' => 'Taiwan (+886)',
	'7' => 'Tajikstan (+7)',
	'66' => 'Thailand (+66)',
	'228' => 'Togo (+228)',
	'676' => 'Tonga (+676)',
	'1868' => 'Trinidad & Tobago (+1868)',
	'216' => 'Tunisia (+216)',
	'90' => 'Turkey (+90)',
	'7' => 'Turkmenistan (+7)',
	'993' => 'Turkmenistan (+993)',
	'1649' => 'Turks & Caicos Islands (+1649)',
	'688' => 'Tuvalu (+688)',
	'256' => 'Uganda (+256)',
	'380' => 'Ukraine (+380)',
	'971' => 'United Arab Emirates (+971)',
	'598' => 'Uruguay (+598)',
	'7' => 'Uzbekistan (+7)',
	'678' => 'Vanuatu (+678)',
	'379' => 'Vatican City (+379)',
	'58' => 'Venezuela (+58)',
	'84' => 'Vietnam (+84)',
	'84' => 'Virgin Islands - British (+1284)',
	'84' => 'Virgin Islands - US (+1340)',
	'681' => 'Wallis & Futuna (+681)',
	'969' => 'Yemen (North)(+969)',
	'967' => 'Yemen (South)(+967)',
	'260' => 'Zambia (+260)',
	'263' => 'Zimbabwe (+263)',
);


$array_shipworkposition=array();
$array_shipworkposition[1]='Position 1';
$array_shipworkposition[2]='Position 2';
$array_shipworkposition[3]='Position 3';
$array_shipworkposition[4]='Position 4';

$array_alertdays=array();
$array_alertdays[7]='7 Days Before Expiry';
$array_alertdays[14]='14 Days Before Expiry';
$array_alertdays[21]='21 Days Before Expiry';
$array_alertdays[28]='28 Days Before Expiry';

$array_category_shore=array();
$array_category_shore[101]='HR, Crewing, Training & Administration';
$array_category_shore[102]='Finance, Accounts & Payroll';
$array_category_shore[103]='Commercial & Business Development';
$array_category_shore[104]='Operations, Projects & Vessel Management';
$array_category_shore[105]='Technical & Dry Docking';
$array_category_shore[106]='QHSE';
$array_category_shore[107]='Insurance, P&I';
$array_category_shore[108]='Purchasing';
$array_category_shore[109]='Management';

$array_category_offshore=array();
$array_category_offshore[1]='Able Seafarer – Deck';
$array_category_offshore[2]='Able Seafarer – Engine';
$array_category_offshore[3]='Able Seaman';
$array_category_offshore[4]='Apprentice';
$array_category_offshore[5]='Bosun';
$array_category_offshore[6]='Caterer';
$array_category_offshore[7]='Chief Caterer';
$array_category_offshore[8]='Chief Cook';
$array_category_offshore[9]='Chief Engineer';
$array_category_offshore[10]='Chief Integrated Rating (CIR)';
$array_category_offshore[11]='Chief Officer';
$array_category_offshore[12]='Cook';
$array_category_offshore[13]='Crane Operator';
$array_category_offshore[14]='Deck Cadet';
$array_category_offshore[15]='Deck hand';
$array_category_offshore[16]='Diver';
$array_category_offshore[17]='SDPO/DPO';
$array_category_offshore[18]='Electrician';
$array_category_offshore[19]='Electrical Cadet';
$array_category_offshore[20]='Engineer Cadet';
$array_category_offshore[21]='ETO';
$array_category_offshore[22]='First Engineer';
$array_category_offshore[23]='Fourth Engineer';
$array_category_offshore[24]='General Purpose Hand (GPH)';
$array_category_offshore[25]='Greaser';
$array_category_offshore[26]='Integrated Rating (IR)';
$array_category_offshore[27]='Master';
$array_category_offshore[28]='Medic';
$array_category_offshore[29]='Ordinary Seaman';
$array_category_offshore[30]='Other';
$array_category_offshore[31]='Provisional Integrated Rating(PIR)';
$array_category_offshore[32]='Rigger';
$array_category_offshore[33]='SDPO';
$array_category_offshore[34]='Second Engineer';
$array_category_offshore[35]='Second Officer';
$array_category_offshore[36]='Security Guard';
$array_category_offshore[37]='Third Engineer';
$array_category_offshore[38]='Third Officer';
$array_category_offshore[39]='Trainee Integrated Rating(TIR)';
$array_category_offshore[40]='Tug Engineer';
$array_category_offshore[41]='Tug Master';

$array_aus_location=array();
$array_aus_location[1]='New South Wales';
$array_aus_location[2]='Norther Territory';
$array_aus_location[3]='Queensland';
$array_aus_location[4]='South Australia';
$array_aus_location[5]='Tasmania';
$array_aus_location[6]='Victoria';
$array_aus_location[7]='Western Australia';

$array_newze_location=array();
$array_newze_location[101]='Auckland';
$array_newze_location[102]='Bay of Plenty';
$array_newze_location[103]='Canterbury';
$array_newze_location[104]='Gisborne';
$array_newze_location[105]='Hawke\'s Bay';
$array_newze_location[106]='Manawatu-Whanganui';
$array_newze_location[107]='Marlborough';
$array_newze_location[108]='Nelson';
$array_newze_location[109]='Northland';
$array_newze_location[110]='Otago';
$array_newze_location[111]='Southland';
$array_newze_location[112]='Taranaki';
$array_newze_location[113]='Tasman';
$array_newze_location[114]='Waikato';
$array_newze_location[115]='West Coast';
$array_newze_location[116]='Wllington';


$array_location_all=array();
$array_location_all[1]='New South Wales';
$array_location_all[2]='Norther Territory';
$array_location_all[3]='Queensland';
$array_location_all[4]='South Australia';
$array_location_all[5]='Tasmania';
$array_location_all[6]='Victoria';
$array_location_all[7]='Western Australia';
$array_location_all[101]='Auckland';
$array_location_all[102]='Bay of Plenty';
$array_location_all[103]='Canterbury';
$array_location_all[104]='Gisborne';
$array_location_all[105]='Hawke\'s Bay';
$array_location_all[106]='Manawatu-Whanganui';
$array_location_all[107]='Marlborough';
$array_location_all[108]='Nelson';
$array_location_all[109]='Northland';
$array_location_all[110]='Otago';
$array_location_all[111]='Southland';
$array_location_all[112]='Taranaki';
$array_location_all[113]='Tasman';
$array_location_all[114]='Waikato';
$array_location_all[115]='West Coast';
$array_location_all[116]='Wllington';

$array_job_section=array();
$array_job_section["Offshore"]='Offshore Jobs';
$array_job_section["Shore"]='Shore Jobs';

$array_job_type=array();
$array_job_type[1]='Full Time';
$array_job_type[2]='Part Time';
$array_job_type[3]='Casual';
$array_job_type[4]='Contract';

$array_competency_certificate=array();
$array_competency_certificate[1]='Master - Reg II/2 - Unlimited';
$array_competency_certificate[2]='Master less than 500 GT';
$array_competency_certificate[3]='Master less than 24 metres';
$array_competency_certificate[4]='Chief mate - Reg 11/2 - Unlimited';
$array_competency_certificate[5]='Mate less than 500 GT';
$array_competency_certificate[6]='Watchkeeper deck';
$array_competency_certificate[7]='Watchkeeper deck less than 500 GT';
$array_competency_certificate[8]='Deck Cadet';
$array_competency_certificate[9]='Chief Engineer class 1';
$array_competency_certificate[10]='Engineer class 2';
$array_competency_certificate[11]='Engineer watchkeeper';
$array_competency_certificate[12]='Electro Technical officer - ETO';
$array_competency_certificate[13]='Engineer cadet';
$array_competency_certificate[14]='Chief integrated rating course';
$array_competency_certificate[15]='Integrated Rating Course - STCW Reg II/5 and III/5';
$array_competency_certificate[16]='Integrated Rating Course - STCW Reg II/4cand III/4';
$array_competency_certificate[17]='Navigational watch rating—STCW Reg II/4';
$array_competency_certificate[18]='Able seafarer deck—STCW Reg II/5';
$array_competency_certificate[19]='Able seafarer engine—STCW Reg III/5';
$array_competency_certificate[20]='Engine room watch rating—STCW Reg III/4';
$array_competency_certificate[21]='Marine Cook';

$array_course_certificate=array();
$array_course_certificate[101]='Advanced / Basic Fire Fighting';
$array_course_certificate[102]='Advanced marine pilots course';
$array_course_certificate[103]='Anchor Handling Familiarisation';
$array_course_certificate[104]='Anchor Handling Safety';
$array_course_certificate[105]='BOSIET/FOET';
$array_course_certificate[106]='Bridge resource management';
$array_course_certificate[107]='CA-EBS';
$array_course_certificate[108]='Confined Space Entry';
$array_course_certificate[109]='Crowd Management';
$array_course_certificate[110]='Designated Security Duties';
$array_course_certificate[111]='Designated security person';
$array_course_certificate[112]='DP Advanced';
$array_course_certificate[113]='DP Basic';
$array_course_certificate[114]='DP Familiarisation';
$array_course_certificate[115]='DP Induction for Engineers';
$array_course_certificate[116]='DP Operator Refresher';
$array_course_certificate[117]='DP Position Reference System';
$array_course_certificate[118]='DP Revalidation';
$array_course_certificate[119]='DP SDP Familirisation Course';
$array_course_certificate[120]='DP Verification of Comptence';
$array_course_certificate[121]='DPO Certificate';
$array_course_certificate[122]='DPO Course';
$array_course_certificate[123]='ECDIS / TECDIS';
$array_course_certificate[124]='Fast Rescue Boat/Crafts';
$array_course_certificate[125]='GMDSS';
$array_course_certificate[126]='Helicopter Refuelling';
$array_course_certificate[127]='High speed craft';
$array_course_certificate[128]='High Voltage Certificate';
$array_course_certificate[129]='HLO';
$array_course_certificate[130]='Hotwork Permit';
$array_course_certificate[131]='HUET';
$array_course_certificate[132]='ISM Familiarisation';
$array_course_certificate[133]='K-POS Maintenance';
$array_course_certificate[134]='Maritime Internal Auditor';
$array_course_certificate[135]='Medical Care / Medical First Aid / First Aid';
$array_course_certificate[136]='Offshore Crane Course';
$array_course_certificate[137]='Offshore Crane operator Assesment';
$array_course_certificate[138]='Offshore Operation Course';
$array_course_certificate[139]='Other';
$array_course_certificate[140]='Passenger ship safety';
$array_course_certificate[141]='Personal Survival Techniques';
$array_course_certificate[142]='Pilot\'s revalidation as for Deck revalidation';
$array_course_certificate[143]='Professional development course';
$array_course_certificate[144]='Proficiency in fast rescue boats';
$array_course_certificate[145]='PSCRB';
$array_course_certificate[146]='PSSR';
$array_course_certificate[147]='Risk Management & Incident Investigation';
$array_course_certificate[148]='Rolls Royce Icon & Azipull Familirisation';
$array_course_certificate[149]='Rolls Royce Icon Maintenance';
$array_course_certificate[150]='Rolls Royce Icon Operator Familirisation';
$array_course_certificate[151]='Safety officer Certificate';
$array_course_certificate[152]='Security Awareness';
$array_course_certificate[153]='Ships Security Officer';
$array_course_certificate[154]='STCW Refresher Course';
$array_course_certificate[155]='Tanker familiarisation (gas)';
$array_course_certificate[156]='Tanker familiarisation (oil & chemical)';
$array_course_certificate[157]='T-BOSIET/T-FOET';
$array_course_certificate[158]='Towing/Anchor Handling Winch operator';
$array_course_certificate[159]='Trade Certificate';
$array_course_certificate[160]='Working at Height';

$array_medical_certificate=array();
$array_medical_certificate[201]='Medical Fitness - AMSA';
$array_medical_certificate[202]='Medical Fitness - Other STCW/ILO';
$array_medical_certificate[203]='Yellow Fever';
$array_medical_certificate[204]='Gisborne';
$array_medical_certificate[205]='Hawke\'s Bay';
$array_medical_certificate[206]='Manawatu-Whanganui';
$array_medical_certificate[207]='Marlborough';
$array_medical_certificate[208]='Nelson';

$array_endorsements_certificate=array();
$array_endorsements_certificate[301]='Certificate of Recognition - AMSA';
$array_endorsements_certificate[302]='Endorsement - Panama';
$array_endorsements_certificate[303]='Endorsement - Norwegian';
$array_endorsements_certificate[304]='Endorsement - Cyprus';
$array_endorsements_certificate[305]='Endorsement - Marshall Island';
$array_endorsements_certificate[306]='Endorsement - Singapore';
$array_endorsements_certificate[307]='Endorsement - Other';

//$array_national_certificate[401]='Passport';
//$array_national_certificate[402]='Driver License';
//$array_national_certificate[403]='National Identity Document';
//$array_national_certificate[404]='Visa Permit';

$array_all_certificate=array();
$array_all_certificate[1]='Master - Reg II/2 - Unlimited';
$array_all_certificate[2]='Master less than 500 GT';
$array_all_certificate[3]='Master less than 24 metres';
$array_all_certificate[4]='Chief mate - Reg 11/2 - Unlimited';
$array_all_certificate[5]='Mate less than 500 GT';
$array_all_certificate[6]='Watchkeeper deck';
$array_all_certificate[7]='Watchkeeper deck less than 500 GT';
$array_all_certificate[8]='Deck Cadet';
$array_all_certificate[9]='Chief Engineer class 1';
$array_all_certificate[10]='Engineer class 2';
$array_all_certificate[11]='Engineer watchkeeper';
$array_all_certificate[12]='Electro Technical officer - ETO';
$array_all_certificate[13]='Engineer cadet';
$array_all_certificate[14]='Chief integrated rating course';
$array_all_certificate[15]='Integrated Rating Course - STCW Reg II/5 and III/5';
$array_all_certificate[16]='Integrated Rating Course - STCW Reg II/4cand III/4';
$array_all_certificate[17]='Navigational watch rating—STCW Reg II/4';
$array_all_certificate[18]='Able seafarer deck—STCW Reg II/5';
$array_all_certificate[19]='Able seafarer engine—STCW Reg III/5';
$array_all_certificate[20]='Engine room watch rating—STCW Reg III/4';
$array_all_certificate[21]='Marine Cook';
$array_all_certificate[101]='Advanced / Basic Fire Fighting';
$array_all_certificate[102]='Advanced marine pilots course';
$array_all_certificate[103]='Anchor Handling Familiarisation';
$array_all_certificate[104]='Anchor Handling Safety';
$array_all_certificate[105]='BOSIET/FOET';
$array_all_certificate[106]='Bridge resource management';
$array_all_certificate[107]='CA-EBS';
$array_all_certificate[108]='Confined Space Entry';
$array_all_certificate[109]='Crowd Management';
$array_all_certificate[110]='Designated Security Duties';
$array_all_certificate[111]='Designated security person';
$array_all_certificate[112]='DP Advanced';
$array_all_certificate[113]='DP Basic';
$array_all_certificate[114]='DP Familiarisation';
$array_all_certificate[115]='DP Induction for Engineers';
$array_all_certificate[116]='DP Operator Refresher';
$array_all_certificate[117]='DP Position Reference System';
$array_all_certificate[118]='DP Revalidation';
$array_all_certificate[119]='DP SDP Familirisation Course';
$array_all_certificate[120]='DP Verification of Comptence';
$array_all_certificate[121]='DPO Certificate';
$array_all_certificate[122]='DPO Course';
$array_all_certificate[123]='ECDIS / TECDIS';
$array_all_certificate[124]='Fast Rescue Boat/Crafts';
$array_all_certificate[125]='GMDSS';
$array_all_certificate[126]='Helicopter Refuelling';
$array_all_certificate[127]='High speed craft';
$array_all_certificate[128]='High Voltage Certificate';
$array_all_certificate[129]='HLO';
$array_all_certificate[130]='Hotwork Permit';
$array_all_certificate[131]='HUET';
$array_all_certificate[132]='ISM Familiarisation';
$array_all_certificate[133]='K-POS Maintenance';
$array_all_certificate[134]='Maritime Internal Auditor';
$array_all_certificate[135]='Medical Care / Medical First Aid / First Aid';
$array_all_certificate[136]='Offshore Crane Course';
$array_all_certificate[137]='Offshore Crane operator Assesment';
$array_all_certificate[138]='Offshore Operation Course';
$array_all_certificate[139]='Other';
$array_all_certificate[140]='Passenger ship safety';
$array_all_certificate[141]='Personal Survival Techniques';
$array_all_certificate[142]='Pilot\'s revalidation as for Deck revalidation';
$array_all_certificate[143]='Professional development course';
$array_all_certificate[144]='Proficiency in fast rescue boats';
$array_all_certificate[145]='PSCRB';
$array_all_certificate[146]='PSSR';
$array_all_certificate[147]='Risk Management & Incident Investigation';
$array_all_certificate[148]='Rolls Royce Icon & Azipull Familirisation';
$array_all_certificate[149]='Rolls Royce Icon Maintenance';
$array_all_certificate[150]='Rolls Royce Icon Operator Familirisation';
$array_all_certificate[151]='Safety officer Certificate';
$array_all_certificate[152]='Security Awareness';
$array_all_certificate[153]='Ships Security Officer';
$array_all_certificate[154]='STCW Refresher Course';
$array_all_certificate[155]='Tanker familiarisation (gas)';
$array_all_certificate[156]='Tanker familiarisation (oil & chemical)';
$array_all_certificate[157]='T-BOSIET/T-FOET';
$array_all_certificate[158]='Towing/Anchor Handling Winch operator';
$array_all_certificate[159]='Trade Certificate';
$array_all_certificate[160]='Working at Height';
$array_all_certificate[201]='Medical Fitness - AMSA';
$array_all_certificate[202]='Medical Fitness - Other STCW/ILO';
$array_all_certificate[203]='Yellow Fever';
$array_all_certificate[204]='Gisborne';
$array_all_certificate[205]='Hawke\'s Bay';
$array_all_certificate[206]='Manawatu-Whanganui';
$array_all_certificate[207]='Marlborough';
$array_all_certificate[208]='Nelson';
$array_all_certificate[301]='Certificate of Recognition - AMSA';
$array_all_certificate[302]='Endorsement - Panama';
$array_all_certificate[303]='Endorsement - Norwegian';
$array_all_certificate[304]='Endorsement - Cyprus';
$array_all_certificate[305]='Endorsement - Marshall Island';
$array_all_certificate[306]='Endorsement - Singapore';
$array_all_certificate[307]='Endorsement - Other';
$array_all_certificate[401]='Passport';
$array_all_certificate[402]='Driver License';
$array_all_certificate[403]='National Identity Document';
$array_all_certificate[404]='Visa Permit';

?>